sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 050605/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 050605/client-test  npm run test

after_success:
  - docker build -t 050605/multi-client ./client
  - docker build -t 050605/multi-server ./server
  - docker build -t 050605/multi-worker ./worker
  - docker build -t 050605/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 050605/multi-client
  - docker push 050605/multi-nginx
  - docker push 050605/multi-server
  - docker push 050605/multi-worker